#!/bin/bash
#
# Copyright (C) 2019 Nikos Mavrogiannopoulos
#
# This file is part of ocserv.
#
# ocserv is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# ocserv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# This tests support for anyconnect's DTLS1.2 support

PKG_CONFIG="${PKG_CONFIG:-/usr/bin/pkg-config}"
CIPHER12_NAME="AES256-GCM-SHA384"
GNUTLS_NAME="(DTLS1.2)-(RSA)-(AES-256-GCM)"

# There is a bug preventing AES256-GCM-SHA384 to work in openconnect
# 8.02.
${PKG_CONFIG} --atleast-version=8.03 openconnect
test $? != 0 && exit 77

. cipher-common.sh

