#!/bin/bash

#echo $USERNAME : $REASON : $DEVICE

env >/tmp/out.$REASON.tmp

verify_env_set() {
	if test -z "${!1}";then
		echo "$1 environment variable was not set" > /tmp/out.$REASON.fail.tmp
		exit 1
	fi
}

verify_env_set "IP_REMOTE"
verify_env_set "REASON"

case "$REASON" in
  connect)
	verify_env_set "USERNAME"
	verify_env_set "USER_AGENT"
	verify_env_set "DEVICE"
	verify_env_set "DEVICE_PLATFORM"
	verify_env_set "DEVICE_TYPE"

	test "${OCSERV_DNS}" = "192.168.1.1 192.168.5.1 " && \
	test "${OCSERV_DNS4}" = "192.168.1.1 192.168.5.1 " && \
	test "${OCSERV_ROUTES}" = "192.168.1.0/255.255.255.0 192.168.5.0/255.255.255.0 " && \
	test "${OCSERV_ROUTES4}" = "192.168.1.0/255.255.255.0 192.168.5.0/255.255.255.0 " && \
	echo "${IP_REMOTE}" > connect.ok
	;;
  disconnect)
	if ! test -z "$DEVICE";then
		test "${OCSERV_DNS}" = "192.168.1.1 192.168.5.1 " && \
		test "${OCSERV_DNS4}" = "192.168.1.1 192.168.5.1 " && \
		test "${OCSERV_ROUTES}" = "192.168.1.0/255.255.255.0 192.168.5.0/255.255.255.0 " && \
		test "${OCSERV_ROUTES4}" = "192.168.1.0/255.255.255.0 192.168.5.0/255.255.255.0 " && \
		echo "${IP_REMOTE}" > disconnect.ok
	fi
	;;
  "host-update")
	echo > host-update.ok
	;;
esac

exit 0
