#!/bin/sh
#
# Copyright (C) 2014 Red Hat
#
# This file is part of ocserv.
#
# ocserv is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# ocserv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ocserv; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

srcdir=${srcdir:-.}
SERV="${SERV:-../src/ocserv}"

#this test can only be run as root
id|grep root >/dev/null 2>&1
if [ $? != 0 ];then
	exit 77
fi

$SERV --version 2>&1|grep gssapi >/dev/null 2>&1
if [ $? != 0 ];then
	exit 77
fi

stop_all() {
        $DOCKER stop test_ocserv_client_kerberos
        $DOCKER rm test_ocserv_client_kerberos
        $DOCKER stop test_ocserv_kerberos
        $DOCKER rm test_ocserv_kerberos
        exit 1
}

CONFIG="kerberos"
DOCKER_DIR=docker-kerberos
IMAGE=ocserv-kerberos-test
IMAGE_NAME=test_ocserv_kerberos
. ./docker-common.sh

$DOCKER run -P --privileged=true --hostname=kerberos.test --add-host='kerberos.test:127.0.0.1' --tty=false -d --name $IMAGE_NAME $IMAGE
if test $? != 0;then
	echo "Cannot run docker image"
	exit 1
fi

echo "ocserv image was run"
#wait for ocserv to server
sleep 5

IP=`$DOCKER inspect $IMAGE_NAME | grep IPAddress | cut -d '"' -f 4`
if test -z "$IP";then
	echo "Detected IP is null!"
	$DOCKER inspect $IMAGE_NAME
	stop
fi
echo "Detected KDC IP: $IP"

# run the client
CONFIG="client"
DOCKER_DIR=docker-kerberos
IMAGE=ocserv-kerberos-client-test
IMAGE_NAME=test_ocserv_client_kerberos
. ./docker-common.sh

$DOCKER run -P --privileged=true --add-host="kerberos.test:$IP" --tty=false -d --name test_ocserv_client_kerberos $IMAGE
if test $? != 0;then
	echo "Could not run client docker image"
	stop_all
fi

CIP=`$DOCKER inspect test_ocserv_client_kerberos | grep IPAddress | cut -d '"' -f 4`
if test -z "$CIP";then
	echo "Detected client IP is null!"
	$DOCKER inspect $IMAGE_NAME
	stop
fi
echo "Detected client IP: $CIP"

if test ! -z "$QUIT_ON_INIT";then
	exit 0
fi

echo "Waiting for client tests"
sleep 100

check_for_file /tmp/ok1 test_ocserv_client_kerberos
if test $? != 0;then
	echo "Kerberos client basic test failed"
	ret=1
fi

check_for_file /tmp/ok2 test_ocserv_client_kerberos
if test $? != 0;then
	echo "Kerberos client TGT freshness test failed"
	ret=1
fi

check_for_file /tmp/group-ok test_ocserv_kerberos
if test $? != 0;then
	echo "Kerberos group name detection test failed"
	ret=1
fi

$DOCKER stop test_ocserv_kerberos
$DOCKER rm test_ocserv_kerberos
$DOCKER stop test_ocserv_client_kerberos
$DOCKER rm test_ocserv_client_kerberos

exit $ret
