#!/bin/bash
#
# Copyright (C) 2018 Red Hat, Inc.
#
# This file is part of ocserv.
#
# ocserv is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# ocserv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuTLS; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

SERV="${SERV:-../src/ocserv}"
srcdir=${srcdir:-.}
PORT=4513

# Test whether more than 128 routes can be read from a config file.

. `dirname $0`/common.sh

echo "Testing ocserv and user route application... "

TMPFILE1=multiple-routes.$$.tmp

rm -f ${TMPFILE1}

launch_simple_server -d 1 -f -c "${srcdir}/data/multiple-routes.config"
PID=$!
wait_server $PID

echo -n "Connecting to obtain cookie (with certificate)... "
( $OPENCONNECT -q localhost:$PORT --sslkey ${srcdir}/certs/user-key.pem -c ${srcdir}/certs/user-cert.pem --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly </dev/null >/dev/null ) ||
	fail $PID "Could not connect with certificate!"

echo ok

echo -n "Re-connecting to get routes... "
timeout 15s $OPENCONNECT -v localhost:$PORT --sslkey ${srcdir}/certs/user-key.pem -c ${srcdir}/certs/user-cert-testuser.pem --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 -s /bin/true </dev/null >${TMPFILE1} 2>&1

echo ok

echo -n "Checking number of routes... "

CONTENTS=`cat ${TMPFILE1}|grep X-CSTP-Split-Include|wc -l`
if test "$CONTENTS" != "256";then
	cat ${TMPFILE1}|grep X-CSTP-Split-Include
	fail $PID "Temporary file contents are not correct; 256 routes were not found"
fi

echo ok

rm -f ${TMPFILE1}
kill $PID
wait

exit 0
