#!/bin/sh
#
# Copyright (C) 2015 Red Hat, Inc.
#
# This file is part of ocserv.
#
# ocserv is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# ocserv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuTLS; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

SERV="${SERV:-../src/ocserv}"
srcdir=${srcdir:-.}
PORT=4441

. `dirname $0`/common.sh

echo "Testing ocserv and SIGHUP behavior... "

cp test-sighup.config test-sighup2.config
launch_simple_server -d 1 -f -c test-sighup2.config
PID=$!

wait_server $PID

echo -n "Connecting to obtain cookie (with certificate)... "
( openconnect -q localhost:$PORT --sslkey ./user-key.pem -c ./user-cert.pem --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly </dev/null >/dev/null 2>&1 ) ||
	fail $PID "Could not connect with certificate!"

echo ok

echo "Reloading server"
kill -HUP $PID
sleep 5

echo -n "Connecting to obtain cookie (with certificate)... "
( openconnect -q localhost:$PORT --sslkey ./user-key.pem -c ./user-cert.pem --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly </dev/null >/dev/null 2>&1 ) ||
	fail $PID "Could not connect with certificate!"

echo ok

sed -i 's/^auth = "certificate"/#auth = "certificate"/g' test-sighup2.config
sed -i 's/^#auth = "plain[.\/test1.passwd]"/auth = "plain[.\/test1.passwd]"/g' test-sighup2.config
echo "Reloading server"
kill -HUP $PID
sleep 5

echo -n "Connecting to obtain cookie (with certificate)... "
( openconnect -q localhost:$PORT --sslkey ./user-key.pem -c ./user-cert.pem --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly </dev/null >/dev/null 2>&1 ) ||
	fail $PID "Could not connect with certificate!"

echo ok

rm -f test-sighup2.config

kill $PID
wait

exit 0
