#!/bin/sh
#
# Copyright (C) 2018 Red Hat, Inc.
#
# This file is part of ocserv.
#
# ocserv is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# ocserv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

SERV="${SERV:-../src/ocserv}"
srcdir=${srcdir:-.}
NO_NEED_ROOT=1
PORT=4432
PIDFILE=ocserv-pid.$$.tmp

. `dirname $0`/common.sh

echo "Testing operation when run on background..."

update_config test1.config
launch_simple_sr_server -d 1 -p ${PIDFILE} --no-chdir -c ${CONFIG}

sleep 3

PID=$(cat ${PIDFILE})
if test -z "${PID}";then
	echo "server did not start"
	exit 1
fi

echo "Server started with PID $PID..."

echo "Connecting to obtain cookie..."
( echo "test" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -q $ADDRESS:$PORT -u test --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly ) ||
	fail $PID "Could not receive cookie from server"

if ! test -f ${PIDFILE};then
	fail $PID "Could not find pid file ${PIDFILE}"
fi


cleanup

exit 0
