#!/bin/sh
#
# Copyright (C) 2013 Nikos Mavrogiannopoulos
#
# This file is part of GnuTLS.
#
# GnuTLS is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3 of the License, or (at
# your option) any later version.
#
# GnuTLS is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuTLS; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

SERV="${SERV:-../src/ocserv}"

. `dirname $0`/common.sh

echo "Testing ocserv and user route application... "

launch_server -d -f -c test-iroute.config & PID=$!
wait_server $PID

echo -n "Connecting to obtain cookie (with certificate)... "
( openconnect -q localhost:4443 --sslkey ./user-key.pem -c ./user-cert.pem --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly </dev/null >/dev/null 2>&1 ) ||
	fail $PID "Could not connect with certificate!"

echo ok

echo -n "Checking if routes have been applied... "

if [ ! -f test-iroute.tmp ];then
	fail $PID "Temporary file cannot be found"
fi

CONTENTS=`cat ./test-iroute.tmp`
if [ "$CONTENTS" != "192.168.1.0/24 vpns0" -a "$CONTENTS" != "192.168.1.0/24 tun0" ];then
	fail $PID "Temporary file contents are not correct"
fi

echo ok

rm -f test-iroute.tmp

kill $PID
wait

exit 0
