#!/bin/sh
#
# Copyright (C) 2015 Nikos Mavrogiannopoulos
#
# This file is part of ocserv.
#
# ocserv is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# ocserv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuTLS; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

SERV="${SERV:-../src/ocserv}"
srcdir=${srcdir:-.}
PORT=4442

. `dirname $0`/common.sh

echo "Testing whether cookie key rotation occurs as expected... "
PIDFILE="${srcdir}/cr$$.pid"
rm -f "${PIDFILE}"

launch_server -d 1 -f -c ${srcdir}/test-cookie-rotation.config & PID=$!
wait_server $PID

echo "Connecting to obtain cookie... "
eval $(echo "test" | $OPENCONNECT -q localhost:$PORT -u test --authenticate --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3)

if [ -z "$COOKIE" ];then
	fail $PID "Could not obtain cookie"
fi

#echo "Cookie: $COOKIE"
sleep 5
echo ""
echo "Connecting with cookie... "
echo "test" | $OPENCONNECT -q -b localhost:$PORT -u test -C "$COOKIE" --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --script=/bin/true --verbose --pid-file "${PIDFILE}" --background

sleep 4

if [ ! -f "${PIDFILE}" ];then
	fail $PID "It was not possible to establish session!"
fi

CPID=`cat "${PIDFILE}"`
kill $CPID
rm -f "${PIDFILE}"

sleep 120
#echo "Cookie: $COOKIE"
echo ""
echo "Connecting with cookie after rekey... "
echo "test" | $OPENCONNECT -q -b localhost:$PORT -u test -C "$COOKIE" --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --script=/bin/true --verbose --pid-file "${PIDFILE}" --background

sleep 4

if [ ! -f "${PIDFILE}" ];then
	fail $PID "It was not possible to establish session!"
fi

CPID=`cat "${PIDFILE}"`
kill $CPID
rm -f "${PIDFILE}"

sleep 120
#echo "Cookie: $COOKIE"
echo ""
echo "Connecting with cookie after 3rd rekey... "
echo "test" | $OPENCONNECT -q -b localhost:$PORT -u test -C "$COOKIE" --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --script=/bin/true --verbose --pid-file "${PIDFILE}" --background

sleep 4

if [ -f "${PIDFILE}" ];then
	CPID=`cat "${PIDFILE}"`
	kill $CPID
	rm -f "${PIDFILE}"
	fail $PID "It was possible to establish session!"
fi

kill $PID
wait

exit 0
