#!/bin/bash
#
# Copyright (C) 2013 Nikos Mavrogiannopoulos
#
# This file is part of ocserv.
#
# ocserv is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# ocserv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuTLS; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

SERV="${SERV:-../src/ocserv}"
srcdir=${srcdir:-.}
PORT=4501

. `dirname $0`/common.sh

echo "Testing ocserv and user route application... "

rm -f ${srcdir}/test-iroute.tmp

launch_server -d 1 -f -c ${srcdir}/test-iroute.config & PID=$!
wait_server $PID

echo -n "Connecting to obtain cookie (with certificate)... "
( $OPENCONNECT -q localhost:$PORT --sslkey ${srcdir}/user-key.pem -c ${srcdir}/user-cert.pem --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly </dev/null ) ||
	fail $PID "Could not connect with certificate!"

echo ok

echo -n "Re-connecting to force script run... "
$OPENCONNECT -q localhost:$PORT --sslkey ${srcdir}/user-key.pem -c ${srcdir}/user-cert.pem --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 -s ./bin/true </dev/null &
kpid=$!
echo ok

sleep 2
kill $kpid

sleep 1
echo -n "Checking if routes have been applied... "

if [ ! -f ${srcdir}/test-iroute.tmp ];then
	fail $PID "Temporary file cannot be found"
fi

CONTENTS=`cat ${srcdir}/test-iroute.tmp`
if [[ "$CONTENTS" =~ "192.168.1.0/24 [vpns|tun]$" ]];then
	fail $PID "Temporary file contents are not correct"
fi

echo ok

rm -f ${srcdir}/test-iroute.tmp

kill $PID
wait

exit 0
