#!/bin/sh
#
# Copyright (C) 2013 Red Hat
#
# This file is part of ocserv.
#
# ocserv is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# ocserv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuTLS; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

SERV="${SERV:-../src/ocserv}"
srcdir=${srcdir:-.}
PORT=4498

. `dirname $0`/common.sh

echo "Testing whether cookies will remain valid during the session time... "
rm -f ${srcdir}/pid.$$

launch_server -d 1 -f -c ${srcdir}/test-cookie-timeout-2.config & PID=$!
wait_server $PID

echo "Connecting to obtain cookie... "
eval `echo "test" | openconnect -q localhost:$PORT -u test --authenticate --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3`

if [ -z "$COOKIE" ];then
	fail $PID "Could not obtain cookie"
fi

#echo "Cookie: $COOKIE"
sleep 10
echo ""
echo "Connecting with cookie... "
echo "test" | openconnect -q -b localhost:$PORT -u test -C "$COOKIE" --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --script=/bin/true --verbose --pid-file ${srcdir}/pid.$$ &

sleep 4

if [ ! -f ${srcdir}/pid.$$ ];then
	fail $PID "It was not possible to establish session!"
fi

CPID=`cat ${srcdir}/pid.$$`
rm -f "${srcdir}/pid.$$"
rm -f "${srcdir}/pid2.$$"

sleep 30
echo ""
echo "Connecting again with cookie (overriding first session)... "
echo "test" | openconnect -b -q localhost:$PORT -u test -C "$COOKIE" --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --script=/bin/true --verbose --pid-file ${srcdir}/pid2.$$ &

sleep 6

kill $CPID
if [ ! -f ${srcdir}/pid2.$$ ];then
	fail $PID "It was not possible to establish second session!"
else
	CPID=`cat ${srcdir}/pid2.$$`
	kill $CPID
	rm -f "${srcdir}/pid2.$$"
	wait $CPID
fi

kill $PID
wait

rm -f ${srcdir}/pid.$$
rm -f ${srcdir}/pid2.$$

exit 0
