#!/bin/sh
#
# Copyright (C) 2013 Nikos Mavrogiannopoulos
#
# This file is part of ocserv.
#
# ocserv is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# ocserv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuTLS; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

SERV="${SERV:-../src/ocserv}"
srcdir=${srcdir:-.}
NO_NEED_ROOT=1

CRLNAME=crl.pem.$$.tmp
CRLTMPLNAME=crl.tmpl.$$.tmp

. `dirname $0`/common.sh

eval "${GETPORT}"

echo "Testing ocserv with certificates... "

rm -f "${CRLNAME}" "${CRLTMPLNAME}"
echo crl_next_update = 999 >"${CRLTMPLNAME}"
echo crl_number = 1 >>"${CRLTMPLNAME}"

certtool --generate-crl --load-ca-privkey "${srcdir}/certs/ca-key.pem" --load-ca-certificate "${srcdir}/certs/ca.pem" \
	--outfile "${CRLNAME}" --template "${CRLTMPLNAME}" >/dev/null 2>&1
if test $? != 0;then
	kill $PID
	exit 77
fi

update_config test3.config
launch_simple_sr_server -d 1 -f -c ${CONFIG}
PID=$!

wait_server $PID

echo -n "Connecting to obtain cookie (without certificate)... "
( LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -q $ADDRESS:$PORT --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly </dev/null >/dev/null 2>&1 ) &&
	fail $PID "Connected without certificate!"

echo "ok (failed as expected)"

echo -n "Connecting to obtain cookie (with invalid certificate)... "
( LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -q $ADDRESS:$PORT --sslkey "${srcdir}/certs/user-key.pem" -c "${srcdir}/certs/user-cert-invalid.pem" --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly </dev/null >/dev/null 2>&1 ) &&
	fail $PID "Connected with invalid certificate!"

echo "ok (failed as expected)"

echo -n "Connecting to obtain cookie (with certificate)... "
( LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -q $ADDRESS:$PORT --sslkey "${srcdir}/certs/user-key.pem" -c "${srcdir}/certs/user-cert.pem" --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly </dev/null >/dev/null 2>&1 ) ||
	fail $PID "Could not connect with certificate!"

echo ok

echo "Try a DER encoded CRL"

certtool --generate-crl --load-ca-privkey "${srcdir}/certs/ca-key.pem" --load-ca-certificate "${srcdir}/certs/ca.pem" \
	--outder --outfile "${CRLNAME}" --template "${CRLTMPLNAME}" >/dev/null 2>&1
if test $? != 0;then
	kill $PID
	exit 77
fi

echo "Reloading server"
kill -HUP $PID
sleep 5

echo -n "Connecting to obtain cookie (with DER CRL)... "
( LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -q $ADDRESS:$PORT --sslkey "${srcdir}/certs/user-key.pem" -c "${srcdir}/certs/user-cert.pem" --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly </dev/null >/dev/null 2>&1 ) ||
	fail $PID "Could not connect with certificate!"

echo ok


#revoke the certificate
certtool --generate-crl --load-ca-privkey "${srcdir}/certs/ca-key.pem" --load-ca-certificate "${srcdir}/certs/ca.pem" \
	--outder --load-certificate "${srcdir}/certs/user-cert.pem" --outfile "${CRLNAME}" --template "${CRLTMPLNAME}" >/dev/null 2>&1
if test $? != 0;then
	cleanup
	exit 77
fi

echo "Reloading server"
kill -HUP $PID
sleep 5

echo -n "Connecting to obtain cookie (with revoked certificate)... "
( LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -q $ADDRESS:$PORT --sslkey "${srcdir}/certs/user-key.pem" -c "${srcdir}/certs/user-cert.pem" --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --cookieonly </dev/null >/dev/null 2>&1 ) &&
	fail $PID "Connected with revoked certificate!"

echo "ok (failed as expected)"

#echo "Normal connection... "
#( echo "test" | LD_PRELOAD=libsocket_wrapper.so $OPENCONNECT -q $ADDRESS:$PORT -u test --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --script=/bin/true ) ||
#	fail $PID "Could not connect to server"

rm -f "${CRLNAME}" "${CRLTMPLNAME}"

cleanup
if test $? != 0;then
	exit 1
fi

exit 0
