#!/bin/bash
#
# Copyright (C) 2020 William Dauchy
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

SERV="${SERV:-../src/ocserv}"
PIDFILE=ocserv-pid.$$.tmp
srcdir=${srcdir:-.}
PORT=4498
LISTEN_NS="ocserv-listen-ns-tmp-$$"
OUTFILE=lsof.$$.tmp
SS=$(which ss)

ADDRESS=10.213.2.1
CLI_ADDRESS=10.213.1.1
VPNNET=172.17.215.0/24
VPNADDR=172.17.215.1

function finish {
  set +e
  echo " * Cleaning up..."
  test -n "${PID}" && kill ${PID} >/dev/null 2>&1
  test -n "${PIDFILE}" && rm -f ${PIDFILE} >/dev/null 2>&1
  test -n "${CONFIG}" && rm -f ${CONFIG} >/dev/null 2>&1
  test -n "${LISTEN_NS}" && ${IP} netns delete ${LISTEN_NS} >/dev/null 2>&1
  test -n "${OUTFILE}" && rm -f ${OUTFILE} >/dev/null 2>&1
}
trap finish EXIT

. `dirname $0`/common.sh
. `dirname $0`/ns.sh

update_config test-namespace-listen.config
if test "$VERBOSE" = 1;then
DEBUG="-d 3"
fi

echo "Seting up listen namespace"
${IP} netns add ${LISTEN_NS}

${CMDNS2} ${SERV} -p ${PIDFILE} -f -c ${CONFIG} ${DEBUG} & PID=$!

sleep 5

${IP} netns exec ${LISTEN_NS} ${SS} -tulwn>${OUTFILE}
grep "LISTEN" ${OUTFILE}
if test $? != 0; then
	echo "ocserv is not listening in the correct namespace!"
	exit 1
fi

kill $PID
wait

exit 0
