#!/bin/sh
#
# Copyright (C) 2019 Nikos Mavrogiannopoulos
#
# This file is part of ocserv.
#
# ocserv is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# ocserv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GnuTLS; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

SERV="${SERV:-../src/ocserv}"
srcdir=${srcdir:-.}
PORT=4500

. `dirname $0`/common.sh

echo "Testing whether max-same-clients=1 allows cookie re-use... "

PIDFILE1="${srcdir}/ci$$-1.pid.tmp"
PIDFILE2="${srcdir}/ci$$-2.pid.tmp"
rm -f "${PIDFILE1}" "${PIDFILE2}"

launch_server -d 1 -f -c "${srcdir}/data/test-max-same-1.config" & PID=$!
wait_server $PID

echo "Connecting to obtain cookie... "
eval `echo "test" | $OPENCONNECT -q localhost:$PORT -u test --authenticate --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3`

if [ -z "$COOKIE" ];then
	fail $PID "Could not obtain cookie"
fi

#echo "Cookie: $COOKIE"

echo "Connecting with cookie... "
echo "test" | $OPENCONNECT -q localhost:$PORT -u test -C "$COOKIE" --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --script=/bin/true --verbose --pid-file "${PIDFILE1}" --background
CPID=$!

sleep 4

echo "Connecting again with same cookie... "
echo "test" | $OPENCONNECT -q localhost:$PORT -b -u test -C "$COOKIE" --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 --script=/bin/true --verbose --pid-file "${PIDFILE2}" --background
C2PID=$!

sleep 4

if [ ! -f "${PIDFILE2}" ];then
	fail $PID "It was not possible to establish session!"
fi

# checking whether server has already terminated $CPID
sleep 1

if [ -f "${PIDFILE1}" ];then
	fail $PID "Initial connection was still running!"
fi

rm -f "${PIDFILE1}" "${PIDFILE2}"

kill $C2PID >/dev/null 2>&1
kill $CPID >/dev/null 2>&1
kill $PID
wait

exit 0
