#!/bin/sh
#
# Copyright (C) 2014 Red Hat
#
# This file is part of ocserv.
#
# ocserv is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# ocserv is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ocserv; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

srcdir=${srcdir:-.}

#this test can only be run as root
id|grep root >/dev/null 2>&1
if [ $? != 0 ];then
	exit 77
fi

UNIX=1
CONFIG="unix"
IMAGE=ocserv-test2
IMAGE_NAME=test_unix
. ./docker-common.sh

$DOCKER run -P --privileged=true -p 6000:6000/udp -p 6001:6001/udp -p 22 -p 6551:6551/udp --tty=false -d --name test_unix $IMAGE
if test $? != 0;then
	echo "Cannot run docker image"
	exit 1
fi

#wait for ocserv to server
sleep 5

IP=`$DOCKER inspect test_unix | grep IPAddress | cut -d '"' -f 4`
if test -z "$IP";then
	echo "Detected IP is null!"
	stop
fi

printf "test\ntest\n" >pass.tmp
openconnect $IP:6551 -u test --passwd-on-stdin --servercert=d66b507ae074d03b02eafca40d35f87dd81049d3 < pass.tmp &
PID=$!

rm -f pass.tmp

#wait for openconnect
sleep 5

# The client IP depends on the username so it shouldn't change.
ping -w 5 192.168.99.0
if test $? != 0;then
	kill $PID
	echo "Cannot ping ocserv"
	stop
fi

ping -w 5 192.168.99.0 -s 1500
if test $? != 0;then
	kill $PID
	echo "Cannot ping ocserv"
	stop
fi

echo "UserKnownHostsFile ./known-hosts.tmp" >config.tmp
printf "#\!/bin/sh\n" >echo-admin.tmp
printf "echo yes" >>echo-admin.tmp
printf "echo root" >>echo-admin.tmp
printf "\n" >>echo-admin.tmp
chmod 755 echo-admin.tmp
export SSH_ASKPASS="./echo-admin.tmp"
setsid ssh -T -F config.tmp root@192.168.99.0 occtl show user test >out.tmp 2>&1
cat out.tmp

printf "#\!/bin/sh\n" >echo-admin.tmp
printf "echo root" >>echo-admin.tmp
printf "\n" >>echo-admin.tmp
chmod 755 echo-admin.tmp
setsid ssh -T -F config.tmp root@192.168.99.0 occtl show user test >out.tmp 2>&1
cat out.tmp
rm -f echo-admin.tmp
rm -f config.tmp
rm -f known-hosts.tmp

grep "Username" out.tmp
if test $? != 0;then
	kill $PID
	echo "could not find user information"
	stop
fi

rm -f out.tmp

# There is an issue in nuttcp that makes it crash under docker if
# /proc/sys/net/ipv4/tcp_adv_win_scale does not exist.

#nuttcp -T 10 -t 192.168.99.0
#if test $? != 0;then
#	kill $PID
#	echo "Cannot send to ocserv"
#	stop
#fi

#nuttcp -T 10 -r 192.168.99.0
#if test $? != 0;then
#	kill $PID
#	echo "Cannot recv from ocserv"
#	stop
#fi
sleep 2

kill $PID

sleep 4

#check whether /tmp/disconnect/ok was created
rm -f ./not-ok
$DOCKER cp test_unix:/tmp/disconnect/not-ok ./
if test -f ./not-ok;then
	echo "There was an issue getting stats"
	stop
fi
rm -f ./not-ok

ret=0

rm -f ./tmp-unix/ok
$DOCKER cp test_unix:/tmp/disconnect/ok ./tmp-unix/
if ! test -f ./tmp-unix/ok;then
	echo "Don't know if stats were received"
	ret=77
else
	echo -n "stats: "
	echo `cat ./tmp-unix/ok`
	rm -rf ./tmp-unix/
fi

$DOCKER stop test_unix
$DOCKER rm test_unix

exit $ret
