#!/bin/sh

if [ "$REASON" = "connect" ];then
	# Disable the firewall for the user's device
	iptables -A INPUT -i $DEVICE -j ACCEPT

	echo "User '$USERNAME' from '$IP_REAL' connected. Local IP is '$IP_REMOTE'"
else
	iptables -D INPUT -i $DEVICE -j ACCEPT

	echo "User '$USERNAME' from '$IP_REAL' disconnected (in: $STATS_BYTES_IN, out: $STATS_BYTES_OUT, time: $STATS_DURATION)."
fi

exit 0
