FROM debian:stretch

RUN apt-get update -y
RUN apt-get install -y libgnutls-deb0-28 liboath0 libprotobuf-c1 libev4
RUN apt-get install -y libwrap0 libpam0g libseccomp2 libdbus-1-3 libreadline5 libnl-route-3-200
RUN apt-get install -y libhttp-parser2.1 libpcl1 libopts25
RUN apt-get install -y libsystemd0 valgrind nuttcp openssh-server bash
RUN apt-get install -y libtalloc2 liblz4-1 less
RUN apt-get install -y freeradius libradcli4
RUN sed 's/PermitRootLogin without-password/PermitRootLogin yes/g' -i /etc/ssh/sshd_config

RUN echo 'root:root' |chpasswd
RUN useradd -m -d /home/admin -s /bin/bash admin
RUN echo 'admin:admin' |chpasswd

RUN mkdir /etc/ocserv


ADD ca.pem /etc/ocserv/
ADD key.pem /etc/ocserv/
ADD cert.pem /etc/ocserv/
ADD cert.pem /etc/ocserv/
ADD ocserv-radius-config.conf /etc/ocserv/ocserv.conf
ADD radiusclient-debian.conf /etc/radiusclient/radiusclient.conf
ADD radius-clients.conf /etc/freeradius/clients.conf
ADD radiusclient-servers /etc/radiusclient/servers
ADD ocserv /usr/sbin/
ADD ocpasswd /usr/bin/
ADD occtl /usr/bin/
ADD myscript /usr/bin/
ADD freeradius-users /etc/freeradius/users
ADD radius-dictionary /etc/radiusclient/dictionary
# It's not possible to use mknod inside a container with the default LXC
# template, so we untar it from this archive.
ADD dev-tun.tgz /dev/

CMD nuttcp -S;/etc/init.d/ssh restart;/usr/sbin/freeradius -X -f >/tmp/freeradius.out 2>&1 & mkdir -p /tmp/disconnect/;usr/sbin/ocserv -d 1 -f;sleep 3600
