FROM debian:jessie

RUN apt-get update;sleep 3
RUN apt-get install -y libgnutls-deb0-28
RUN apt-get install -y libprotobuf-c1
RUN apt-get install -y libwrap0 libpam0g libseccomp2 libdbus-1-3 libreadline5 libnl-route-3-200
RUN apt-get install -y libhttp-parser2.1 libpcl1 libopts25 autogen
RUN apt-get install -y libsystemd-daemon0 valgrind nuttcp openssh-server bash
RUN apt-get install -y libtalloc2
RUN apt-get install -y liblz4-1
RUN apt-get install -y libfreeradius-client2
RUN apt-get install -y libkrb5-3 less
RUN sed 's/PermitRootLogin without-password/PermitRootLogin yes/g' -i /etc/ssh/sshd_config

RUN echo 'root:root' |chpasswd
RUN useradd -m -d /home/admin -s /bin/bash admin
RUN echo 'admin:admin' |chpasswd
EXPOSE 5000
EXPOSE 5000/udp
EXPOSE 5001
EXPOSE 5001/udp
EXPOSE 5551
EXPOSE 5551/udp
EXPOSE 22

RUN mkdir /etc/ocserv

ADD key.pem /etc/ocserv/
ADD cert.pem /etc/ocserv/
ADD ocserv.conf /etc/ocserv/
ADD passwd /etc/ocserv/
ADD ocserv /usr/sbin/
ADD ocpasswd /usr/bin/
ADD occtl /usr/bin/
ADD myscript /usr/bin/
# It's not possible to use mknod inside a container with the default LXC
# template, so we untar it from this archive.
ADD dev-tun.tgz /dev/

CMD nuttcp -S;/etc/init.d/ssh restart;mkdir -p /tmp/disconnect/;usr/sbin/ocserv -d 1 -f;sleep 3600
